export const INDIAN_CITIES = [
  // Metros & Major Hubs
  { name: 'Delhi', state: 'Delhi' },
  { name: 'New Delhi', state: 'Delhi' },
  { name: 'Mumbai', state: 'Maharashtra' },
  { name: 'Bengaluru', state: 'Karnataka' },
  { name: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Kolkata', state: 'West Bengal' },
  { name: 'Hyderabad', state: 'Telangana' },
  { name: 'Pune', state: 'Maharashtra' },
  { name: 'Ahmedabad', state: 'Gujarat' },
  
  // Maharashtra state
  { name: 'Sangli', state: 'Maharashtra' },
  { name: 'Satara', state: 'Maharashtra' },
  { name: 'Kolhapur', state: 'Maharashtra' },
  { name: 'Solapur', state: 'Maharashtra' },
  { name: 'Nagpur', state: 'Maharashtra' },
  { name: 'Nashik', state: 'Maharashtra' },
  { name: 'Thane', state: 'Maharashtra' },
  { name: 'Aurangabad', state: 'Maharashtra' },
  { name: 'Amravati', state: 'Maharashtra' },
  { name: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Jalgaon', state: 'Maharashtra' },
  { name: 'Akola', state: 'Maharashtra' },
  { name: 'Latur', state: 'Maharashtra' },
  { name: 'Dhule', state: 'Maharashtra' },
  { name: 'Ahmednagar', state: 'Maharashtra' },
  { name: 'Chandrapur', state: 'Maharashtra' },
  { name: 'Parbhani', state: 'Maharashtra' },
  { name: 'Jalna', state: 'Maharashtra' },
  { name: 'Bhusawal', state: 'Maharashtra' },
  { name: 'Ratnagiri', state: 'Maharashtra' },
  { name: 'Nanded', state: 'Maharashtra' },
  { name: 'Miraj', state: 'Maharashtra' },
  { name: 'Gondia', state: 'Maharashtra' },
  { name: 'Wardha', state: 'Maharashtra' },
  
  // Gujarat
  { name: 'Surat', state: 'Gujarat' },
  { name: 'Vadodara', state: 'Gujarat' },
  { name: 'Rajkot', state: 'Gujarat' },
  { name: 'Bhavnagar', state: 'Gujarat' },
  { name: 'Jamnagar', state: 'Gujarat' },
  { name: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Junagadh', state: 'Gujarat' },
  { name: 'Anand', state: 'Gujarat' },
  { name: 'Navsari', state: 'Gujarat' },
  { name: 'Morbi', state: 'Gujarat' },
  { name: 'Bharuch', state: 'Gujarat' },
  { name: 'Vapi', state: 'Gujarat' },
  { name: 'Bhuj', state: 'Gujarat' },
  { name: 'Porbandar', state: 'Gujarat' },
  
  // Rajasthan
  { name: 'Jaipur', state: 'Rajasthan' },
  { name: 'Jodhpur', state: 'Rajasthan' },
  { name: 'Kota', state: 'Rajasthan' },
  { name: 'Bikaner', state: 'Rajasthan' },
  { name: 'Ajmer', state: 'Rajasthan' },
  { name: 'Udaipur', state: 'Rajasthan' },
  { name: 'Bhilwara', state: 'Rajasthan' },
  { name: 'Alwar', state: 'Rajasthan' },
  { name: 'Bharatpur', state: 'Rajasthan' },
  { name: 'Sikar', state: 'Rajasthan' },
  { name: 'Pali', state: 'Rajasthan' },
  { name: 'Sri Ganganagar', state: 'Rajasthan' },
  { name: 'Mount Abu', state: 'Rajasthan' },
  { name: 'Jaisalmer', state: 'Rajasthan' },
  
  // Uttar Pradesh
  { name: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Kanpur', state: 'Uttar Pradesh' },
  { name: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Meerut', state: 'Uttar Pradesh' },
  { name: 'Allahabad', state: 'Uttar Pradesh' },
  { name: 'Bareilly', state: 'Uttar Pradesh' },
  { name: 'Aligarh', state: 'Uttar Pradesh' },
  { name: 'Moradabad', state: 'Uttar Pradesh' },
  { name: 'Saharanpur', state: 'Uttar Pradesh' },
  { name: 'Gorakhpur', state: 'Uttar Pradesh' },
  { name: 'Noida', state: 'Uttar Pradesh' },
  { name: 'Firozabad', state: 'Uttar Pradesh' },
  { name: 'Jhansi', state: 'Uttar Pradesh' },
  { name: 'Muzaffarnagar', state: 'Uttar Pradesh' },
  { name: 'Mathura', state: 'Uttar Pradesh' },
  { name: 'Rampur', state: 'Uttar Pradesh' },
  { name: 'Shahjahanpur', state: 'Uttar Pradesh' },
  { name: 'Ayodhya', state: 'Uttar Pradesh' },
  
  // Madhya Pradesh
  { name: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'Jabalpur', state: 'Madhya Pradesh' },
  { name: 'Gwalior', state: 'Madhya Pradesh' },
  { name: 'Ujjain', state: 'Madhya Pradesh' },
  { name: 'Sagar', state: 'Madhya Pradesh' },
  { name: 'Dewas', state: 'Madhya Pradesh' },
  { name: 'Satna', state: 'Madhya Pradesh' },
  { name: 'Ratlam', state: 'Madhya Pradesh' },
  { name: 'Rewa', state: 'Madhya Pradesh' },
  { name: 'Katni', state: 'Madhya Pradesh' },
  { name: 'Singrauli', state: 'Madhya Pradesh' },
  { name: 'Burhanpur', state: 'Madhya Pradesh' },
  { name: 'Khandwa', state: 'Madhya Pradesh' },
  { name: 'Khajuraho', state: 'Madhya Pradesh' },
  
  // Bihar & Jharkhand
  { name: 'Patna', state: 'Bihar' },
  { name: 'Gaya', state: 'Bihar' },
  { name: 'Bhagalpur', state: 'Bihar' },
  { name: 'Muzaffarpur', state: 'Bihar' },
  { name: 'Darbhanga', state: 'Bihar' },
  { name: 'Ranchi', state: 'Jharkhand' },
  { name: 'Jamshedpur', state: 'Jharkhand' },
  { name: 'Dhanbad', state: 'Jharkhand' },
  { name: 'Bokaro', state: 'Jharkhand' },
  { name: 'Deoghar', state: 'Jharkhand' },
  { name: 'Hazaribagh', state: 'Jharkhand' },
  
  // West Bengal & Odisha
  { name: 'Howrah', state: 'West Bengal' },
  { name: 'Durgapur', state: 'West Bengal' },
  { name: 'Asansol', state: 'West Bengal' },
  { name: 'Siliguri', state: 'West Bengal' },
  { name: 'Darjeeling', state: 'West Bengal' },
  { name: 'Kharagpur', state: 'West Bengal' },
  { name: 'Haldia', state: 'West Bengal' },
  { name: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Cuttack', state: 'Odisha' },
  { name: 'Rourkela', state: 'Odisha' },
  { name: 'Brahmapur', state: 'Odisha' },
  { name: 'Sambalpur', state: 'Odisha' },
  { name: 'Puri', state: 'Odisha' },
  
  // Punjab & Haryana
  { name: 'Ludhiana', state: 'Punjab' },
  { name: 'Amritsar', state: 'Punjab' },
  { name: 'Jalandhar', state: 'Punjab' },
  { name: 'Patiala', state: 'Punjab' },
  { name: 'Bathinda', state: 'Punjab' },
  { name: 'Faridabad', state: 'Haryana' },
  { name: 'Gurugram', state: 'Haryana' },
  { name: 'Panipat', state: 'Haryana' },
  { name: 'Ambala', state: 'Haryana' },
  { name: 'Rohtak', state: 'Haryana' },
  { name: 'Hisar', state: 'Haryana' },
  { name: 'Karnal', state: 'Haryana' },
  
  // Karnataka
  { name: 'Mysore', state: 'Karnataka' },
  { name: 'Hubli', state: 'Karnataka' },
  { name: 'Dharwad', state: 'Karnataka' },
  { name: 'Mangalore', state: 'Karnataka' },
  { name: 'Belgaum', state: 'Karnataka' },
  { name: 'Gulbarga', state: 'Karnataka' },
  { name: 'Davanagere', state: 'Karnataka' },
  { name: 'Bellary', state: 'Karnataka' },
  { name: 'Bijapur', state: 'Karnataka' },
  { name: 'Shimoga', state: 'Karnataka' },
  { name: 'Tumkur', state: 'Karnataka' },
  { name: 'Raichur', state: 'Karnataka' },
  { name: 'Udupi', state: 'Karnataka' },
  { name: 'Hampi', state: 'Karnataka' },
  
  // Andhra Pradesh & Telangana
  { name: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { name: 'Vijayawada', state: 'Andhra Pradesh' },
  { name: 'Guntur', state: 'Andhra Pradesh' },
  { name: 'Nellore', state: 'Andhra Pradesh' },
  { name: 'Kurnool', state: 'Andhra Pradesh' },
  { name: 'Rajahmundry', state: 'Andhra Pradesh' },
  { name: 'Tirupati', state: 'Andhra Pradesh' },
  { name: 'Kakinada', state: 'Andhra Pradesh' },
  { name: 'Kadapa', state: 'Andhra Pradesh' },
  { name: 'Warangal', state: 'Telangana' },
  { name: 'Nizamabad', state: 'Telangana' },
  { name: 'Karimnagar', state: 'Telangana' },
  { name: 'Khammam', state: 'Telangana' },
  { name: 'Ramagundam', state: 'Telangana' },
  
  // Tamil Nadu & Kerala
  { name: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'Madurai', state: 'Tamil Nadu' },
  { name: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { name: 'Salem', state: 'Tamil Nadu' },
  { name: 'Tirunelveli', state: 'Tamil Nadu' },
  { name: 'Tiruppur', state: 'Tamil Nadu' },
  { name: 'Vellore', state: 'Tamil Nadu' },
  { name: 'Erode', state: 'Tamil Nadu' },
  { name: 'Thoothukudi', state: 'Tamil Nadu' },
  { name: 'Kanyakumari', state: 'Tamil Nadu' },
  { name: 'Ooty', state: 'Tamil Nadu' },
  { name: 'Thiruvananthapuram', state: 'Kerala' },
  { name: 'Kochi', state: 'Kerala' },
  { name: 'Kozhikode', state: 'Kerala' },
  { name: 'Thrissur', state: 'Kerala' },
  { name: 'Kollam', state: 'Kerala' },
  { name: 'Alappuzha', state: 'Kerala' },
  { name: 'Kannur', state: 'Kerala' },
  { name: 'Munnar', state: 'Kerala' },
  
  // Others
  { name: 'Guwahati', state: 'Assam' },
  { name: 'Dibrugarh', state: 'Assam' },
  { name: 'Silchar', state: 'Assam' },
  { name: 'Chandigarh', state: 'Chandigarh' },
  { name: 'Raipur', state: 'Chhattisgarh' },
  { name: 'Bhilai', state: 'Chhattisgarh' },
  { name: 'Bilaspur', state: 'Chhattisgarh' },
  { name: 'Korba', state: 'Chhattisgarh' },
  { name: 'Goa', state: 'Goa' },
  { name: 'Panaji', state: 'Goa' },
  { name: 'Shimla', state: 'Himachal Pradesh' },
  { name: 'Manali', state: 'Himachal Pradesh' },
  { name: 'Dharamshala', state: 'Himachal Pradesh' },
  { name: 'Srinagar', state: 'Jammu and Kashmir' },
  { name: 'Jammu', state: 'Jammu and Kashmir' },
  { name: 'Leh', state: 'Ladakh' },
  { name: 'Dehradun', state: 'Uttarakhand' },
  { name: 'Haridwar', state: 'Uttarakhand' },
  { name: 'Roorkee', state: 'Uttarakhand' },
  { name: 'Rishikesh', state: 'Uttarakhand' },
  { name: 'Pondicherry', state: 'Puducherry' },
  { name: 'Agartala', state: 'Tripura' },
  { name: 'Shillong', state: 'Meghalaya' },
  { name: 'Imphal', state: 'Manipur' },
  { name: 'Aizawl', state: 'Mizoram' },
  { name: 'Port Blair', state: 'Andaman and Nicobar Islands' },
];
